[PRMT-1147] Configured canary build pipeline

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -21,6 +21,13 @@ function check_env {
   fi
 }
 
+function check_nhs_service {
+  if [[ -z "${NHS_SERVICE}" ]]; then
+    echo "Must set NHS_SERVICE"
+    exit 1
+  fi
+}
+
 function configure_service_url {
   if [[ -z "${NHS_ENVIRONMENT}" ]]; then
     export SERVICE_URL=http://${NHS_SERVICE}:3000
@@ -42,6 +49,16 @@ function configure_local_envs {
 function get_aws_account_id {
     AWS_ACCOUNT_ID=$(dojo -c Dojofile-infra "aws sts get-caller-identity | jq -r .Account")
  }
+
+function get_aws_ssm_secret {
+   secret_id=$1
+   json=$(dojo -c Dojofile-infra "aws ssm get-parameter --with-decryption --region $AWS_DEFAULT_REGION --name $secret_id")
+   if [ $? != 0 ]; then
+     >&2 echo "Failed to obtain AWS secret from SSM: $secret_id"
+     exit 5
+   fi
+   echo $json | jq -r ".Parameter.Value"
+}
 
 ############################
 # Docker Related Functions #
@@ -98,12 +115,52 @@ function tf_apply {
   terraform output -json > tf-out.json
 }
 
+####################
+# Script Functions #
+####################
+
+function send_canary_update_message {
+  check_nhs_service
+  node scripts/send-canary-update.js $(npm outdated --parseable)
+}
+
+function configure_hangout_webhook {
+  export GOOGLE_CHAT_CANARY_WEBHOOK=$(get_aws_ssm_secret "/repo/prod/user-input/gocd-google-chat-canary-webhook")
+  if [ -z "${GOOGLE_CHAT_CANARY_WEBHOOK}" ]; then
+    echo "Unable to obtain GOOGLE_CHAT_CANARY_WEBHOOK from AWS"
+    exit 5
+  fi
+}
+
 ###########
 ## TASKS ##
 ###########
 
 command="$1"
 case "${command}" in
+  _dep)
+      npm install
+      npm audit
+      ;;
+  dep)
+      dojo "./tasks _dep"
+      ;;
+  _list_outdated)
+      npm install
+      npm outdated > outdated-dependencies.txt || send_canary_update_message
+      ;;
+  list_outdated)
+      configure_hangout_webhook
+      dojo "./tasks _list_outdated"
+      ;;
+  update_package_json)
+      dojo "npx npm-check-updates -u"
+      ;;
+  send_dead_canary_message)
+      check_nhs_service
+      configure_hangout_webhook
+      dojo "node scripts/send-canary-error.js"
+      ;;
   _test_unit)
       npm install
       npm run test:unit
